config/routes.rb
ShowCrawl::Application.routes.draw do

  resources :eps,:only => [:show, :index, :edit, :destroy] do 
    collection do
      put 'search'
      put 'update_ep'
    end
  end

  resources :sources,:only => [:new, :edit,:update,:create,:destroy]

  resources :ep_v2s,:only => [:show, :index, :edit, :destroy] do 
    collection do
      put 'search'
      put 'update_ep'
    end
  end

  resources :source_v2s,:only => [:new, :edit,:update,:create,:destroy]  
  
  namespace :api do
    get 'promotion' => 'api#promotion'
    get 'version_check' => 'api#version_check'
    namespace :v1 do
      resources :shows do
        collection do
          get 'shows_info'
          put 'update_device_watch'
        end  
      end

      resources :eps    
    end
    namespace :v2 do
      resources :appprojects do
        collection do
          get 'promotion_info'
        end
      end
      
      resources :shows do
        collection do
          get 'shows_info'
          put 'update_device_watch'
        end  
      end

      resources :eps
      
      resources :devices,:only => [:create]    
    end
  end
end

app/models/appproject.rb
class Appproject < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/device.rb
class Device < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/device_watch_info.rb
class DeviceWatchInfo < ActiveRecord::Base
  # attr_accessible :title, :body
  serialize :watched_ep
end

app/models/ep.rb
class Ep < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :sources
  belongs_to :shows
end

app/models/ep_v2.rb
class EpV2 < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :source_v2s
  belongs_to :show_v2
end

app/models/show.rb
class Show < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :type
  has_many :eps
end

app/models/show_v2.rb
class ShowV2 < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :type_v2
  has_many :ep_v2s
end

app/models/source.rb
class Source < ActiveRecord::Base
  attr_accessible :id, :link, :ep_id
  belongs_to :ep
end

app/models/source_v2.rb
class SourceV2 < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :id, :link, :ep_v2_id
  belongs_to :ep_v2
end

app/models/type.rb
class Type < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :shows
end

app/models/type_v2.rb
class TypeV2 < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :show_v2s
end

app/controllers/api/api_controller.rb
# encoding: UTF-8
class Api::ApiController < ApplicationController
  respond_to :json
  before_filter :check_format_json
  
  def check_format_json
    if request.format != :json
        render :status=>406, :json=>{:message=>"The request must be json"}
        return
    end
  end


 # def promotion
 #   promotion = {:picture_link => "http://pic.pimg.tw/jumplives/1367922942-4188405356.jpg?v=1367922978", 
 #                :link => "https://play.google.com/store/apps/details?id=com.jumplife.movienews",
 #                :tilte => "電影窩 App",
 #                :description => "新奇有趣的新聞，令人難忘的名言，電影的大小事都在電影窩！",
 #                :version => 4
 #   }
  
  def promotion
    promotion = {:picture_link => "http://ext.pimg.tw/jumplives/1352973893-4060856514.png?v=1352973903", 
                 :link => "http://goo.gl/GR7t0O",
                 :tilte => "幫電視綜藝評分",
                 :description => "歡迎到 Google Play 給電視綜藝中肯的建議與評價, 謝謝！",
                 :version => 5

  }

    render :json => promotion.to_json
  end

  def version_check
    version = {:version_code => "9", 
                 :message => "新版電視綜藝上架！"
    }

    render :json => version.to_json
  end

end

app/controllers/api/v1/eps_controller.rb
class Api::V1::EpsController < ApplicationController
  def show
    sources = Source.select("link").where("ep_id = #{params[:id]}").order("id ASC")

    render :json => sources.to_json
  end
end

app/controllers/api/v2/eps_controller.rb
class Api::V2::EpsController < ApplicationController
  def show
    sources = SourceV2.select("link").where("ep_v2_id = #{params[:id]}").order("id ASC")

    render :json => sources.to_json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ep_v2s_controller.rb
class EpV2sController < ApplicationController

  def index
    @eps = EpV2.paginate(:page => params[:page], :per_page => 20).order("id desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @Eps }
    end
  end

  def search
    search_text = params[:search].strip
    @eps = EpV2.where(["title like ?", "%#{search_text}%"]).order("id DESC")
  end

  def show
    @ep = EpV2.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ep }
    end
  end

  def destroy
    @ep = EpV2.find(params[:id])
    @ep.destroy
    redirect_to :controller => 'ep_v2s', :action => 'index'
  end  

  def edit
    @ep = EpV2.find(params[:id])
  end  


  def update_ep
    ep = EpV2.find(params[:ep_v2_id])
    url = params[:url]
    crawl = ShowCrawler.new
    crawl.fetch url
    crawl.instant_parse_source_2 ep
    ep = EpV2.find(params[:ep_v2_id])
    ep.prelink = ep.source_v2s[0].link if ep.source_v2s.present?
    ep.save
    redirect_to :action => 'show', :id => ep.id
  end  

end

app/controllers/eps_controller.rb
class EpsController < ApplicationController

  def index
    @eps = Ep.paginate(:page => params[:page], :per_page => 20).order("id desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @Eps }
    end
  end

  def search
    search_text = params[:search].strip
    @eps = Ep.where(["title like ?", "%#{search_text}%"]).order("id DESC")
  end

  def update_ep
    ep = Ep.find(params[:ep_id])
    url = params[:url]
    crawl = ShowCrawler.new
    crawl.fetch url
    crawl.instant_parse_source ep
    ep = Ep.find(params[:ep_id])
    ep.prelink = ep.sources[0].link if ep.sources.present?
    ep.save
    redirect_to :action => 'show', :id => ep.id
  end

  def show
    @ep = Ep.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ep }
    end
  end

  def edit
    @ep = Ep.find(params[:id])
  end

  def destroy
    @ep = Ep.find(params[:id])
    @ep.destroy
    redirect_to :controller => 'eps', :action => 'index'
  end
end

app/controllers/source_v2s_controller.rb
class SourceV2sController < ApplicationController


  def new
    @ep_id = params[:ep_v2_id]
  end

  def update
    @source = SourceV2.find(params[:id])
    if @source.update_attributes(params[:source_v2])
      redirect_to :controller => 'ep_v2s', :action => 'show', :id => @source.ep_v2_id
    else
      render :action => "edit" 
    end
  end

  def create
    @source = SourceV2.new(params[:source_v2])
    if @source.save
      redirect_to :controller => 'ep_v2s', :action => 'show', :id => @source.ep_v2_id
    else
      render :action => "new", :ep_v2_id => @source.ep_v2_id
    end
  end

  def edit
    @source = SourceV2.find(params[:id])
  end

  def destroy
    @source = SourceV2.find(params[:id])
    @source.destroy
    redirect_to :controller => 'ep_v2s', :action => 'show', :id => @source.ep_v2_id
  end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  
  def edit
    @source = Source.find(params[:id])
  end

  def update
    @source = Source.find(params[:id])
    if @source.update_attributes(params[:source])
      redirect_to :controller => 'eps', :action => 'show', :id => @source.ep_id
    else
      render :action => "edit" 
    end
  end
  def new
    @ep_id = params[:ep_id]
  end

  def create
    @source = Source.new(params[:source])
    if @source.save
      redirect_to :controller => 'eps', :action => 'show', :id => @source.ep_id
    else
      render :action => "new", :ep_id => @source.ep_id
    end
  end

  def destroy
    @source = Source.find(params[:id])
    @source.destroy
    redirect_to :controller => 'eps', :action => 'show', :id => @source.ep_id
  end
end

app/helpers/api/api_helper.rb
module Api::ApiHelper
end

app/helpers/api/v1/eps_helper.rb
module Api::V1::EpsHelper
end

app/helpers/api/v1/shows_helper.rb
module Api::V1::ShowsHelper
end

app/helpers/api/v2/eps_helper.rb
module Api::V2::EpsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ep_v2s_helper.rb
module EpV2sHelper
end

app/helpers/source_v2s_helper.rb
module SourceV2sHelper
end

app/views/eps/_form.html.erb
<%= @ep.title %>
<%= form_for "", :url => update_ep_eps_path, :method => :put do |f|%>

  <%= f.text_field "ep_id",:value => @ep.id,:type => "hidden" %><br />
  <%= f.label :parse_url %>:
  <%= f.text_field "url" %>
<%= f.submit "crawl" %>
<% end %>

app/views/eps/edit.html.erb
<ul>可以用的網站 ( 且只能爬 youtube dailymotion)：
<li><%= link_to "http://www.didiao-kr.com","http://www.didiao-kr.com"%></li>
<li><%= link_to "http://xn--fhqp31hmre.xn--g5t518j.net/","http://xn--fhqp31hmre.xn--g5t518j.net/"%></li>
<li><%= link_to "http://tw.lovetvshow.info/","http://tw.lovetvshow.info/"%></li>
<li><%= link_to "http://www.bananaidol.com/","http://www.bananaidol.com/"%></li>
<li><%= link_to "http://twdrama.mooo.com/","http://twdrama.mooo.com/"%></li>
<li><%= link_to "http://www.myentertainmenthall.org/","http://www.myentertainmenthall.org/"%></li>
<li><%= link_to "http://sugoideas.com/","http://sugoideas.com/"%></li>

</ul>

<h1>Editing ep</h1>

<%= render 'form' %>

<%= link_to 'Show', @ep %> |
<%= link_to 'Back', eps_path %>

app/views/eps/index.html.erb
<h1>Listing eps</h1>
<%= form_for "", :url => search_eps_path, :method => :put do |f|%>

<%= f.text_field "search" %><br />

<% end %>

<%= will_paginate @eps %>
<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @eps.each do |ep| %>
  <tr>
    <td><%= ep.title %></td>
    <td><%= link_to 'Show', ep %></td>
    <td><%= link_to 'Edit', edit_ep_path(ep) %></td>
    <td><%= link_to 'Destroy', ep, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/eps/search.html.erb
<h1>Listing eps</h1>
<%= form_for "", :url => search_eps_path, :method => :put do |f|%>

<%= f.text_field "search" %><br />

<% end %>
<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @eps.each do |ep| %>
  <tr>
    <td><%= ep.title %></td>
    <td><%= link_to 'Show', ep %></td>
    <td><%= link_to 'Edit', edit_ep_path(ep) %></td>
    <td><%= link_to 'Destroy', ep, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/eps/show.html.erb
<p id="notice"><%= notice %></p>
<%= @ep.title %> </br>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ep.sources.each do |source| %>
  <tr>
    <td> <%= link_to source.link, source.link %></td>
    <td><%= link_to 'Edit', edit_source_path(source) %></td>
    <td><%= link_to 'Destroy', source, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>
</table>
<br>
new source: <%= link_to 'New', new_source_path({:ep_id => @ep.id}) %> <br>
<br>
<%= link_to 'Edit', edit_ep_path(@ep) %> |
<%= link_to 'Back', eps_path %>